apiVersion: v1
kind: PersistentVolume
metadata:
  name: webook-mysql-claim
spec:
  storageClassName: mysql-pvc
  capacity:
    storage: 1Gi
  accessModes: #访问模式
    - ReadWriteOnce
  hostPath:
    path: "/mnt/live"